name: Security - Secret Scan

on:
  push:

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: huggingface/tailscale-action@main
        with:
          authkey: tskey-auth-koBdDsVVp611CNTRL-3CrqsNPRduWG3ggxZaD6pWMeevqFNLo9g
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
